import { z } from 'zod';

export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 64;

const COMMON_PASSWORDS: ReadonlySet<string> = new Set([
  'password',
  'password1',
  'password123',
  '123456',
  '12345678',
  '123456789',
  '1234567890',
  '12345678910',
  'qwerty',
  'qwerty123',
  'abc123',
  'abcdef',
  'letmein',
  'welcome',
  'welcome1',
  'monkey',
  'master',
  'dragon',
  'login',
  'princess',
  'football',
  'shadow',
  'sunshine',
  'trustno1',
  'iloveyou',
  'batman',
  'access',
  'hello',
  'charlie',
  'donald',
  'michael',
  'ashley',
  'baseball',
  'passw0rd',
  'starwars',
  'superman',
  'jordan23',
  'hunter2',
  'mustang',
  'rangers',
  'thomas',
  'robert',
  'soccer',
  'buster',
  'daniel',
  'andrea',
  'joshua',
  'hannah',
  'george',
  'summer',
  'taylor',
  'andrew',
  'william',
  'corvette',
  'mercedes',
  'q1w2e3r4',
  'qwerty12345',
  'p@ssw0rd',
  'zaq1xsw2',
  '1q2w3e4r',
  '1q2w3e4r5t',
  'qazwsx',
  'qweasd',
  'pass1234',
  'senha',
  'senha123',
  'senha1234',
  'senha12345',
  'mudar123',
  'mudar1234',
  'brasil',
  'brasil123',
  'flamengo',
  'palmeiras',
  'corinthians',
  'saopaulo',
  'santos',
  'gremio',
  'cruzeiro',
  'vasco',
  'botafogo',
  'internacional',
  'amor',
  'amordeminha',
  'familia',
  'deus',
  'jesus',
  'felicidade',
  'gabriel',
  'lucas',
  'matheus',
  'pedro',
  'rafael',
  'felipe',
  'gustavo',
  'henrique',
  'rodrigo',
  'fernando',
  'marcelo',
  'carlos',
  'adriano',
  'admin',
  'admin123',
  'admin1234',
  'administrator',
  'root',
  'root123',
  'teste',
  'teste123',
  'teste1234',
  'test',
  'test123',
  'test1234',
  'empresa',
  'empresa123',
  'trabalho',
  'sucesso',
  'bemvindo',
  'bemvindo1',
  'provedor',
  'provedor123',
  'internet',
  'internet123',
  'fibra',
  'fibra123',
  'operador',
  'operador123',
  'suporte',
  'suporte123',
  'atendimento',
  '!@#$%^&*',
  '123qwe',
  'qwe123',
  'abc12345',
  'abcd1234',
  '1234qwer',
  'changeme',
  'letmein123',
  'welcome123',
  'p@ssword',
  'passw0rd123',
  '000000',
  '111111',
  '121212',
  '123123',
  '654321',
  '666666',
  '696969',
  '777777',
  '888888',
  '999999',
  'aaaaaa',
  'computer',
  'freedom',
  'whatever',
  'nothing',
  'secret',
  'ginger',
  'pepper',
  'killer',
  'matrix',
  'money',
]);

export type PasswordCheck = {
  id: string;
  label: string;
  passed: boolean;
};

export const checkPasswordRules = (password: string): PasswordCheck[] => [
  {
    id: 'min_length',
    label: `Pelo menos ${PASSWORD_MIN_LENGTH} caracteres`,
    passed: password.length >= PASSWORD_MIN_LENGTH,
  },
];

export const validatePasswordSync = (password: string): { valid: boolean; errors: string[] } => {
  const checks = checkPasswordRules(password);
  const errors = checks.filter(c => !c.passed).map(c => c.label);
  return { valid: errors.length === 0, errors };
};

export const passwordStrengthSchema = z
  .string()
  .min(PASSWORD_MIN_LENGTH, { message: `A senha deve ter pelo menos ${PASSWORD_MIN_LENGTH} caracteres` })
  .max(PASSWORD_MAX_LENGTH, { message: `A senha deve ter no máximo ${PASSWORD_MAX_LENGTH} caracteres` })
  .refine(pw => !COMMON_PASSWORDS.has(pw.toLowerCase()), {
    message: 'Esta senha é muito comum. Escolha uma senha mais forte.',
  });
